name: 'linear_b_dbt'
version: '1.0.0'
config-version: 2

profile: 'linear_b_dbt'

model-paths: ["models"]

models:
  linear_b_dbt:
    smoke:
      +materialized: view
    staging:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
    marts:
      +materialized: table